fix: ip rate limit
Github api uses common ip address which reaches the rate limit even
before starting one so switching to website based version extraction.

  echo "Latest Version is: $latest_tag"
  echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV
  echo "VERSION_NO_V=$latest_tag" >> $GITHUB_ENV
  shell: /usr/bin/bash -e {0}
Attempting to fetch tag (Attempt 1)...
Warning: Invalid response. API said: {"message":"API rate limit exceeded
for 52.234.43.178. (But here's the good news: Authenticated requests get
a higher rate limit. Check out the documentation for more
details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
Retrying in 20 seconds...
Error: Process completed with exit code 1.
0s